### ISSUE TITLE
No leer los stacks del fichero de entrada se considera como trampa por nueve de cada diez dentistas 

### ISSUE THREAD

**Issue by alvarogonzalezsotillo** [lantoli/AdventOfCode#1]
No leer los stacks del fichero de entrada se considera como trampa por nueve de cada diez dentistas

https://github.com/lantoli/AdventOfCode/blob/eb9bc617eb40a023018ab0fc1ed5f9454349ff40/2022_ts/05_supply_stacks.ts#L10

**Comment by lantoli** [comment]
llevas toda la razón :-)  preferí centrarme en el algoritmo que en parsear la entrada por no dedicarle tanto tiempo
