### ISSUE TITLE
Tenía que haber tirado yo también por vectores unidad 

### ISSUE THREAD

**Issue by alvarogonzalezsotillo** [lantoli/AdventOfCode#2]
te ha quedado bastante más recogidito.

https://github.com/lantoli/AdventOfCode/blob/23275850088c8fc1dca82d82486aa957fb6d4f06/2022_ts/08_treetop_tree_house.ts#L9

**Comment by lantoli** [comment]
je je, gracias.  el tuyo también me gusta como te ha quedado
